#定义服务应用名称
spring:
  application:
    name: eureka-server

server:
  port: 8761

#定义eureka服务端
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


